import { useMemo, useState } from 'react'

const A='/Crown-Oil-Hier/'
const product={name:'Crown Hair Oil',price:119,size:'100 ml',image:`${A}assets/hero-detail.jpg`}
const ingredients=[['الأرغان','ترطيب ونعومة ولمعان للشعر الجاف والمتعب.'],['الروزماري','جزء من روتين متوازن للعناية بفروة الرأس.'],['زيت الزيتون','يساعد على تغذية الشعر وتقليل مظهر الجفاف.']]
const faqs=[['هل يناسب جميع أنواع الشعر؟','صُمم Crown Hair Oil ليكون جزءًا من روتين العناية لمختلف أنواع الشعر. اختبري كمية صغيرة أولًا إذا كانت فروة رأسك حساسة.'],['كم مرة يستخدم؟','ابدئي بمرتين إلى ثلاث مرات أسبوعيًا وعدّلي الكمية والتكرار حسب احتياج شعرك.'],['كيف أستخدم الزيت؟','قسّمي الشعر، ضعي كمية مناسبة، دلّكي فروة الرأس بلطف ثم وزّعي ما يلزم على الأطراف وفق روتينك.'],['ما حجم العبوة؟','العبوة المعروضة حاليًا 100 مل.'],['كيف يتم الشحن والدفع؟','يتم تأكيد خيارات الشحن والدفع والتكلفة النهائية في صفحة إتمام الطلب.']]

function Header({count,onCart}){const[open,setOpen]=useState(false);return <><div className="announcement">توصيل داخل المملكة العربية السعودية · الأسعار تشمل الضريبة</div><header><a className="brand" href="#top"><img src={`${A}assets/logo.jpg`} alt="Crown Hair Oil"/><span>CROWN<small>HAIR OIL</small></span></a><nav className={open?'open':''}><a href="#product">المنتج</a><a href="#ingredients">المكونات</a><a href="#results">النتائج</a><a href="#reviews">التقييمات</a><a href="#faq">الأسئلة الشائعة</a></nav><div className="header-actions"><button className="cart-button" onClick={onCart}>السلة <b>{count}</b></button><button className="menu" onClick={()=>setOpen(!open)} aria-label="القائمة">☰</button></div></header></>}
function Qty({value,setValue}){return <div className="qty"><button onClick={()=>setValue(Math.max(1,value-1))} aria-label="تقليل الكمية">−</button><span>{value}</span><button onClick={()=>setValue(value+1)} aria-label="زيادة الكمية">+</button></div>}
function Cart({open,onClose,qty,setQty,onCheckout}){return <div className={`cart-layer ${open?'show':''}`} onClick={onClose}><aside className="cart" onClick={e=>e.stopPropagation()}><div className="cart-head"><h2>سلة التسوق</h2><button onClick={onClose} aria-label="إغلاق السلة">×</button></div><div className="cart-item"><img src={product.image} alt={product.name}/><div><b>{product.name}</b><small>{product.size}</small><strong>{product.price} ر.س</strong><Qty value={qty} setValue={setQty}/></div></div><div className="cart-total"><span>المجموع الفرعي</span><b>{product.price*qty} ر.س</b></div><small>الشحن يُحسب عند إتمام الطلب.</small><button className="primary full" onClick={onCheckout}>إتمام الطلب</button></aside></div>}
function Checkout({qty,onBack}){const total=product.price*qty;return <main className="checkout"><button className="back" onClick={onBack}>← العودة للمتجر</button><div className="checkout-grid"><section><p className="eyebrow">SECURE CHECKOUT</p><h1>إتمام الطلب</h1><h3>بيانات التواصل</h3><div className="form-grid"><input placeholder="الاسم الكامل"/><input placeholder="رقم الجوال"/><input placeholder="البريد الإلكتروني"/><input placeholder="المدينة"/><input placeholder="الحي"/><input placeholder="الشارع" className="wide"/></div><h3>طريقة الدفع</h3><div className="payment"><label><input type="radio" name="pay" defaultChecked/> بطاقة / مدى / Apple Pay <small>يتم ربط بوابة الدفع في مرحلة الإنتاج.</small></label><label><input type="radio" name="pay"/> الدفع عند الاستلام</label></div></section><aside className="summary"><h3>ملخص الطلب</h3><div className="summary-product"><img src={product.image} alt={product.name}/><span>{product.name}<small>{product.size} · الكمية {qty}</small></span><b>{total} ر.س</b></div><div><span>المجموع الفرعي</span><b>{total} ر.س</b></div><div><span>الشحن</span><span>يُحسب لاحقًا</span></div><hr/><div className="grand"><span>الإجمالي</span><b>{total} ر.س</b></div><button className="primary full" disabled title="يتطلب ربط بوابة الدفع">الدفع غير مفعّل في النسخة التجريبية</button><p className="secure">🔒 لن يتم تحصيل أي دفعة حتى ربط بوابة دفع حقيقية وآمنة.</p></aside></div></main>}

export default function App(){const[cartOpen,setCartOpen]=useState(false),[qty,setQty]=useState(1),[checkout,setCheckout]=useState(false),[faq,setFaq]=useState(0);const count=useMemo(()=>qty,[qty]);if(checkout)return <Checkout qty={qty} onBack={()=>setCheckout(false)}/>;return <div id="top"><Header count={count} onCart={()=>setCartOpen(true)}/><Cart open={cartOpen} onClose={()=>setCartOpen(false)} qty={qty} setQty={setQty} onCheckout={()=>{setCartOpen(false);setCheckout(true)}}/>
<main>
<section className="hero"><div className="hero-copy"><p className="eyebrow">BOTANICAL HAIR & SCALP OIL</p><h1>العناية بشعرك<br/><em>تبدأ من الجذور.</em></h1><p className="lead">مزيج نباتي غني بزيت الأرغان والروزماري والزيتون، صُمم ليكون طقسًا بسيطًا للعناية بالشعر وفروة الرأس.</p><div className="rating">★★★★★ <span>تجربة Crown للعناية اليومية</span></div><div className="price">119 <small>ر.س · 100 مل</small></div><div className="hero-actions"><a className="primary" href="#product">تسوّقي الآن</a><a className="secondary" href="#ingredients">اكتشفي المكونات</a></div><div className="micro"><span>✓ زيوت نباتية مختارة</span><span>✓ لجميع أنواع الشعر</span><span>✓ توصيل داخل المملكة</span></div></div><div className="hero-visual"><div className="halo"></div><img src={`${A}assets/hero-detail.jpg`} alt="عبوة Crown Hair Oil"/><span className="botanical b1">☘</span><span className="botanical b2">❧</span></div></section>
<section className="trust"><span>ARGAN OIL</span><i>✦</i><span>ROSEMARY</span><i>✦</i><span>OLIVE OIL</span><i>✦</i><span>SAUDI DELIVERY</span></section>
<section className="section why"><p className="eyebrow">WHY CROWN</p><h2>روتين أقل. عناية أكثر.</h2><div className="cards"><article><b>01</b><h3>تغذية</h3><p>زيوت مختارة لدعم مظهر الشعر الصحي ضمن روتين عناية متوازن.</p></article><article><b>02</b><h3>ترطيب</h3><p>يساعد على تقليل مظهر الجفاف ومنح الشعر ملمسًا أكثر نعومة.</p></article><article><b>03</b><h3>لمعان</h3><p>لمسة نهائية تمنح الشعر مظهرًا حيويًا ولمعانًا طبيعيًا.</p></article><article><b>04</b><h3>فروة الرأس</h3><p>تدليك الزيت يحوّل العناية بفروة الرأس إلى طقس أسبوعي بسيط.</p></article></div></section>
<section id="ingredients" className="section ingredients"><div className="section-title"><div><p className="eyebrow">WHAT'S INSIDE</p><h2>ثلاثة مكونات.<br/>فلسفة واحدة.</h2></div><p>بدل قائمة طويلة ومعقدة، نسلط الضوء على قلب تركيبة Crown النباتية.</p></div><div className="ingredient-grid">{ingredients.map((x,i)=><article key={x[0]}><span>0{i+1}</span><div className={`ingredient-art ing${i}`}></div><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
<section id="product" className="section product"><div className="product-image"><img src={`${A}assets/hero-detail.jpg`} alt="Crown Hair Oil 100ml"/></div><div className="product-copy"><p className="eyebrow">THE SIGNATURE OIL</p><h2>Crown Hair Oil</h2><p className="muted">Botanical Hair & Scalp Oil · 100 ml</p><div className="stars">★★★★★</div><p>زيت عناية نباتي للشعر وفروة الرأس، بتركيبة دافئة تجمع الأرغان والروزماري والزيتون في خطوة واحدة سهلة.</p><div className="product-price">119 <small>ر.س</small></div><div className="buy-row"><Qty value={qty} setValue={setQty}/><button className="primary" onClick={()=>setCartOpen(true)}>أضيفي للسلة</button></div><button className="buy-now" onClick={()=>setCheckout(true)}>اشتري الآن</button><div className="product-trust"><span>🔒 دفع آمن عند التفعيل</span><span>🚚 توصيل داخل المملكة</span><span>↩ سياسة استرجاع واضحة</span></div></div></section>
<section id="results" className="section results"><div className="section-title"><div><p className="eyebrow">CROWN COMMUNITY</p><h2>نتائج من المجتمع</h2></div><p>صور النتائج يجب أن تكون حقيقية ومصرحًا باستخدامها. لا نعرض وعودًا زمنية غير موثقة.</p></div><div className="result-grid">{[1,2,3,4,5].map(n=><figure key={n}><img src={`${A}Hair after-before ${n}.jpg`} alt={`نتيجة استخدام Crown ${n}`}/><figcaption>تجربة عميلة · Before / After</figcaption></figure>)}</div></section>
<section className="section ritual"><div><p className="eyebrow">THE RITUAL</p><h2>ثلاث خطوات<br/>لروتين Crown.</h2></div><ol><li><b>01</b><span><strong>قسّمي الشعر</strong>للوصول إلى فروة الرأس بسهولة.</span></li><li><b>02</b><span><strong>ضعي ودلّكي</strong>استخدمي كمية مناسبة ودلّكي بلطف.</span></li><li><b>03</b><span><strong>أكملي روتينك</strong>وزّعي ما يلزم على الأطراف حسب احتياج شعرك.</span></li></ol></section>
<section id="reviews" className="section reviews"><p className="eyebrow">REVIEWS</p><h2>الثقة تُبنى بالتجربة.</h2><div className="review-placeholder"><span>★★★★★</span><h3>مكان مخصص للتقييمات الموثقة</h3><p>لن ننشر أسماء أو تقييمات وهمية. عند توفر تقييمات العملاء الحقيقية تظهر هنا مع حالة Verified Purchase.</p></div></section>
<section id="faq" className="section faq"><p className="eyebrow">FAQ</p><h2>أسئلة شائعة</h2>{faqs.map((x,i)=><article className={faq===i?'active':''} key={x[0]} onClick={()=>setFaq(faq===i?-1:i)}><button><span>{x[0]}</span><b>{faq===i?'−':'+'}</b></button>{faq===i&&<p>{x[1]}</p>}</article>)}</section>
<section className="final-cta"><div><p className="eyebrow">YOUR CROWN. YOUR RITUAL.</p><h2>امنحي شعرك<br/>العناية التي يستحقها.</h2><p>خطوة نباتية بسيطة يمكن أن تصبح الجزء المفضل من روتينك.</p><button className="primary" onClick={()=>setCartOpen(true)}>تسوّقي Crown الآن · 119 ر.س</button></div><img src={`${A}assets/hero-dark-crop.jpg`} alt="Crown Hair Oil"/></section>
</main><footer><div className="footer-brand"><img src={`${A}assets/logo.jpg`} alt="Crown Hair Oil"/><b>CROWN<small>HAIR OIL</small></b><p>Botanical care for your crown.</p></div><div><h4>Crown</h4><a href="#ingredients">المكونات</a><a href="#results">النتائج</a><a href="#reviews">التقييمات</a></div><div><h4>المساعدة</h4><a href="#faq">الأسئلة الشائعة</a><a href={`${A}shipping-returns.html`}>الشحن والاسترجاع</a><a href={`${A}contact.html`}>تواصل معنا</a></div><div><h4>قانوني</h4><a href={`${A}privacy.html`}>الخصوصية</a><a href={`${A}terms.html`}>الشروط والأحكام</a></div><div className="copyright">© 2026 Crown Hair Oil · Saudi Arabia · SAR</div></footer><div className="mobile-buy"><span><b>119 ر.س</b><small>Crown Hair Oil</small></span><button onClick={()=>setCartOpen(true)}>أضيفي للسلة</button></div></div>}
