import { useEffect, useMemo, useState } from 'react'
import { CONTENT_API, DEFAULT_CONTENT, mergeContent } from './siteContent.js'

const API='https://asubcanztloxiddshakz.supabase.co/functions/v1/crown-admin-api'
const BASE='/Crown-Oil-Hier/'
const CART_KEY='crown_cart_v2'
const fallbackProduct={id:'fallback-crown',slug:'crown-hair-oil',name_ar:'Crown Hair Oil',name_en:'Crown Hair Oil',description_ar:DEFAULT_CONTENT.product.description,description_en:'',price_sar:DEFAULT_CONTENT.product.price,size_label:DEFAULT_CONTENT.product.size,sku:'CRN-OIL-100',stock_qty:0,active:true,product_images:[{url:DEFAULT_CONTENT.product.image,alt_text:'Crown Hair Oil',position:0}]}
const money=v=>`${Number(v||0).toLocaleString('ar-SA',{maximumFractionDigits:2})} ر.س`
const imageOf=p=>p?.product_images?.[0]?.url||DEFAULT_CONTENT.product.image

function useCatalog(){
 const[products,setProducts]=useState([]),[loading,setLoading]=useState(true)
 useEffect(()=>{fetch(`${API}/public/products`).then(r=>r.ok?r.json():Promise.reject()).then(d=>setProducts(d.products||[])).catch(()=>setProducts([fallbackProduct])).finally(()=>setLoading(false))},[])
 return{products,loading}
}
function useContent(){const[content,setContent]=useState(DEFAULT_CONTENT);useEffect(()=>{fetch(CONTENT_API).then(r=>r.ok?r.json():Promise.reject()).then(r=>r.content&&setContent(mergeContent(DEFAULT_CONTENT,r.content))).catch(()=>{})},[]);return content}
function useCart(products){
 const[cart,setCart]=useState(()=>{try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}})
 useEffect(()=>{if(!products.length)return;setCart(prev=>prev.map(x=>{const p=products.find(y=>y.id===x.productId);if(!p)return null;const max=Math.max(0,Number(p.stock_qty||0));return max?{...x,qty:Math.min(Math.max(1,x.qty),max)}:null}).filter(Boolean))},[products])
 useEffect(()=>{localStorage.setItem(CART_KEY,JSON.stringify(cart))},[cart])
 const add=(p,qty=1)=>{const max=Math.max(0,Number(p.stock_qty||0));if(!max)return;setCart(prev=>{const hit=prev.find(x=>x.productId===p.id);return hit?prev.map(x=>x.productId===p.id?{...x,qty:Math.min(max,x.qty+qty)}:x):[...prev,{productId:p.id,qty:Math.min(max,qty)}]})}
 const setQty=(id,qty)=>{const p=products.find(x=>x.id===id);const max=Math.max(0,Number(p?.stock_qty||0));setCart(prev=>qty<=0||!max?prev.filter(x=>x.productId!==id):prev.map(x=>x.productId===id?{...x,qty:Math.min(max,qty)}:x))}
 const detailed=cart.map(x=>({ ...x, product:products.find(p=>p.id===x.productId)})).filter(x=>x.product)
 return{cart,detailed,add,setQty,count:cart.reduce((s,x)=>s+x.qty,0),total:detailed.reduce((s,x)=>s+Number(x.product.price_sar||0)*x.qty,0)}
}

function Brand(){return <a className="ms-brand" href={BASE}><span className="ms-logo"><img src={`${BASE}crown-logo.png`} alt="Crown Hair Oil"/></span><span>CROWN<small>HAIR OIL</small></span></a>}
function Header({count,onCart}){return <><div className="ms-announcement">توصيل داخل المملكة العربية السعودية · الأسعار تشمل الضريبة</div><header className="ms-header"><Brand/><nav><a href={BASE}>الرئيسية</a><a href={`${BASE}shop/`}>المتجر</a><a href={`${BASE}#ingredients`}>المكونات</a><a href={`${BASE}#faq`}>الأسئلة الشائعة</a></nav><button className="ms-cart-button" onClick={onCart}>السلة <b>{count}</b></button></header></>}
function Footer(){return <footer className="ms-footer"><Brand/><p>Botanical Hair & Scalp Care</p><div><a href={`${BASE}shipping-returns.html`}>الشحن والاسترجاع</a><a href={`${BASE}contact.html`}>تواصلي معنا</a><a href={`${BASE}privacy.html`}>الخصوصية</a><a href={`${BASE}terms.html`}>الشروط</a></div><small>© 2026 CROWN HAIR OIL · SAUDI ARABIA</small></footer>}
function CartDrawer({open,onClose,cart}){return <div className={`ms-cart-layer ${open?'show':''}`} onClick={onClose}><aside onClick={e=>e.stopPropagation()}><header><div><small>YOUR BAG</small><h2>سلة التسوق</h2></div><button onClick={onClose}>×</button></header>{cart.detailed.length? <><div className="ms-cart-items">{cart.detailed.map(({product,qty})=><article key={product.id}><img src={imageOf(product)} alt={product.name_ar}/><div><b>{product.name_ar||product.name_en}</b><small>{product.size_label} · {product.sku}</small><strong>{money(product.price_sar)}</strong><div className="ms-qty"><button onClick={()=>cart.setQty(product.id,qty-1)}>−</button><span>{qty}</span><button disabled={qty>=Number(product.stock_qty)} onClick={()=>cart.setQty(product.id,qty+1)}>+</button></div></div><button className="ms-remove" onClick={()=>cart.setQty(product.id,0)}>حذف</button></article>)}</div><div className="ms-cart-total"><span>المجموع</span><b>{money(cart.total)}</b></div><button className="ms-primary ms-full" disabled>إتمام الطلب — قريبًا</button><p className="ms-note">لن يتم تحصيل أي مبلغ قبل تفعيل بوابة الدفع الإنتاجية. الكميات مرتبطة بالمخزون المتاح حاليًا.</p></>:<div className="ms-empty">السلة فارغة حاليًا.</div>}</aside></div>}
function ProductCard({p,onAdd}){const stock=Number(p.stock_qty||0),out=stock<=0;return <article className="ms-product-card"><a className="ms-card-image" href={`${BASE}product/?slug=${encodeURIComponent(p.slug)}`}><img src={imageOf(p)} alt={p.product_images?.[0]?.alt_text||p.name_ar}/>{out&&<span>نفد المخزون</span>}</a><div className="ms-card-copy"><small>{p.size_label||p.sku}</small><h3><a href={`${BASE}product/?slug=${encodeURIComponent(p.slug)}`}>{p.name_ar||p.name_en}</a></h3><p>{p.description_ar||p.description_en||''}</p><div><b>{money(p.price_sar)}</b><button disabled={out} onClick={()=>onAdd(p)}>{out?'غير متاح':'أضيفي للسلة'}</button></div></div></article>}
function ProductsGrid({products,onAdd,loading}){if(loading)return <div className="ms-loading">جاري تحميل المنتجات...</div>;if(!products.length)return <div className="ms-empty">لا توجد منتجات نشطة حاليًا.</div>;return <div className="ms-products-grid">{products.map(p=><ProductCard key={p.id} p={p} onAdd={onAdd}/>)}</div>}

function Home({content,products,loading,onAdd}){return <main>
 <section className="ms-hero"><div><p className="ms-eyebrow">{content.hero.eyebrow}</p><h1>{content.hero.titleLine1}<br/><em>{content.hero.titleLine2}</em></h1><p>{content.hero.description}</p><div className="ms-hero-actions"><a className="ms-primary" href={`${BASE}shop/`}>تسوّقي المجموعة</a><a className="ms-secondary" href="#ingredients">اكتشفي المكونات</a></div><div className="ms-micro">{content.hero.micro.map(x=><span key={x}>✓ {x}</span>)}</div></div><div className="ms-hero-image"><img src={content.hero.image} alt="Crown Hair Oil"/></div></section>
 <section className="ms-trust">{content.trust.map(x=><span key={x}>{x}</span>)}</section>
 <section className="ms-section"><div className="ms-section-head"><div><p className="ms-eyebrow">SHOP CROWN</p><h2>اختاري روتينك.</h2></div><a href={`${BASE}shop/`}>عرض كل المنتجات ←</a></div><ProductsGrid products={products} onAdd={onAdd} loading={loading}/></section>
 <section id="ingredients" className="ms-section ms-soft"><div className="ms-section-head"><div><p className="ms-eyebrow">{content.ingredients.eyebrow}</p><h2>{content.ingredients.titleLine1}<br/>{content.ingredients.titleLine2}</h2></div><p>{content.ingredients.intro}</p></div><div className="ms-ingredients">{content.ingredients.items.map((x,i)=><article key={i}>{x.image?<img src={x.image} alt={x.name}/>:<div className="ms-botanical">{x.name.slice(0,1)}</div>}<h3>{x.name}</h3><p>{x.copy}</p></article>)}</div></section>
 <section className="ms-section ms-ritual"><div><p className="ms-eyebrow">{content.ritual.eyebrow}</p><h2>{content.ritual.titleLine1}<br/>{content.ritual.titleLine2}</h2><p>{content.ritual.intro}</p></div><ol>{content.ritual.steps.map(s=><li key={s.number}><b>{s.number}</b><span><strong>{s.title}</strong>{s.copy}</span></li>)}</ol></section>
 <section id="faq" className="ms-section ms-faq"><p className="ms-eyebrow">FAQ</p><h2>{content.faq.title}</h2>{content.faq.items.map((x,i)=><details key={i}><summary>{x.question}</summary><p>{x.answer}</p></details>)}</section>
 </main>}
function Shop({products,loading,onAdd}){return <main className="ms-shop"><section className="ms-shop-head"><p className="ms-eyebrow">CROWN COLLECTION</p><h1>المتجر</h1><p>جميع منتجات Crown النشطة. حالة التوفر مرتبطة بالمخزون الفعلي.</p></section><section className="ms-section"><ProductsGrid products={products} onAdd={onAdd} loading={loading}/></section></main>}
function ProductPage({products,loading,onAdd}){const slug=new URLSearchParams(location.search).get('slug')||'';const p=products.find(x=>x.slug===slug);const[active,setActive]=useState(0);useEffect(()=>setActive(0),[slug]);if(loading)return <main className="ms-product-page"><div className="ms-loading">جاري تحميل المنتج...</div></main>;if(!p)return <main className="ms-product-page"><div className="ms-empty"><h1>المنتج غير موجود</h1><a href={`${BASE}shop/`}>العودة للمتجر</a></div></main>;const imgs=p.product_images?.length?p.product_images:[{url:DEFAULT_CONTENT.product.image,alt_text:p.name_ar}],stock=Number(p.stock_qty||0),out=stock<=0;return <main className="ms-product-page"><a className="ms-back" href={`${BASE}shop/`}>← العودة للمتجر</a><section className="ms-product-detail"><div className="ms-gallery"><figure><img src={imgs[Math.min(active,imgs.length-1)].url} alt={imgs[Math.min(active,imgs.length-1)].alt_text||p.name_ar}/></figure>{imgs.length>1&&<div className="ms-thumbs">{imgs.map((img,i)=><button className={active===i?'active':''} key={img.id||i} onClick={()=>setActive(i)}><img src={img.url} alt=""/></button>)}</div>}</div><div className="ms-detail-copy"><p className="ms-eyebrow">{p.sku}</p><h1>{p.name_ar||p.name_en}</h1>{p.name_en&&p.name_en!==p.name_ar&&<small>{p.name_en}</small>}<p className="ms-description">{p.description_ar||p.description_en}</p><div className="ms-detail-price">{money(p.price_sar)} <span>{p.size_label}</span></div><div className={`ms-stock ${out?'out':''}`}>{out?'نفد المخزون':stock<=5?`متبقي ${stock} فقط`:`متوفر · ${stock} في المخزون`}</div><button className="ms-primary ms-full" disabled={out} onClick={()=>onAdd(p)}>{out?'غير متاح حاليًا':'أضيفي للسلة'}</button><div className="ms-detail-trust"><span>✓ السعر يشمل الضريبة</span><span>✓ توصيل داخل المملكة</span><span>✓ الكمية مرتبطة بالمخزون</span></div></div></section></main>}

export default function MultiStoreApp(){const content=useContent(),{products,loading}=useCatalog(),cart=useCart(products),[cartOpen,setCartOpen]=useState(false);const mode=useMemo(()=>location.pathname.includes('/product/')?'product':location.pathname.includes('/shop/')?'shop':'home',[]);const add=p=>{cart.add(p);setCartOpen(true)};useEffect(()=>{document.title=mode==='shop'?'Crown Hair Oil | المتجر':mode==='product'?'Crown Hair Oil | المنتج':content.seo.title},[mode,content.seo.title]);return <div className="ms-app" dir="rtl"><Header count={cart.count} onCart={()=>setCartOpen(true)}/><CartDrawer open={cartOpen} onClose={()=>setCartOpen(false)} cart={cart}/>{mode==='shop'?<Shop products={products} loading={loading} onAdd={add}/>:mode==='product'?<ProductPage products={products} loading={loading} onAdd={add}/>:<Home content={content} products={products} loading={loading} onAdd={add}/>}<Footer/></div>}
