import { useEffect,useMemo,useState } from 'react'
const API='https://asubcanztloxiddshakz.supabase.co/functions/v1/crown-bank-transfer-api'
const TOKEN_KEY='crown_admin_session'
const token=()=>sessionStorage.getItem(TOKEN_KEY)||''
async function request(path,options={}){const r=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||'request_failed'),{status:r.status,data:d});return d}
const money=v=>`${Number(v||0).toLocaleString('ar-SA',{maximumFractionDigits:2})} ر.س`
const date=v=>v?new Date(v).toLocaleString('ar-SA'):'—'
const labels={under_review:'بانتظار التحقق',confirmed:'تم تأكيد الدفع',rejected:'مرفوض'}
export default function BankTransferReview(){
 const[items,setItems]=useState([]),[active,setActive]=useState('under_review'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[note,setNote]=useState(''),[reason,setReason]=useState(''),[matched,setMatched]=useState(false),[selected,setSelected]=useState(null)
 const filtered=useMemo(()=>items.filter(x=>x.status===active),[items,active]),pending=items.filter(x=>x.status==='under_review').length
 async function load(){setLoading(true);setError('');try{const d=await request('/admin/submissions');setItems(d.submissions||[]);if(selected){const next=(d.submissions||[]).find(x=>x.id===selected.id);setSelected(next||null)}}catch(e){setError(e.status===401?'انتهت جلسة الإدارة. سجّل الدخول من محرر الموقع أولًا.':'تعذر تحميل التحويلات البنكية.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 async function confirm(){if(!selected||!matched)return;setBusy('confirm');setError('');try{await request(`/admin/submissions/${selected.id}/confirm`,{method:'POST',body:JSON.stringify({bankMatched:true,note})});setMatched(false);setNote('');await load()}catch(e){setError(e.data?.error==='bank_match_confirmation_required'?'يجب تأكيد مطابقة المبلغ في الحساب البنكي أولًا.':'تعذر تأكيد التحويل.')}finally{setBusy('')}}
 async function reject(){if(!selected||!reason.trim())return;setBusy('reject');setError('');try{await request(`/admin/submissions/${selected.id}/reject`,{method:'POST',body:JSON.stringify({reason,note})});setReason('');setNote('');setMatched(false);await load()}catch{setError('تعذر رفض التحويل.')}finally{setBusy('')}}
 return <div className="commerce-shell bank-review-admin">
  <aside className="commerce-side"><div className="commerce-title"><small>BANK TRANSFER REVIEW</small><h2>التحويلات البنكية</h2><p>راجعي الإيصال ثم طابقي المبلغ فعليًا في الحساب البنكي قبل تأكيد أي طلب.</p></div><nav>{Object.entries(labels).map(([k,v])=><button key={k} className={active===k?'active':''} onClick={()=>{setActive(k);setSelected(null)}}>{v} <b className="review-count">{items.filter(x=>x.status===k).length}</b></button>)}</nav><div className="commerce-side-note"><b>{pending}</b><span>تحويل يحتاج مراجعة</span></div></aside>
  <main className="commerce-main"><header><div><small>CROWN FINANCE OPERATIONS</small><h1>{labels[active]}</h1></div><button onClick={load}>تحديث البيانات</button></header>{error&&<div className="commerce-error">{error}</div>}{loading?<div className="commerce-loading">جاري تحميل التحويلات...</div>:<div className="bank-review-grid"><section className="commerce-panel bank-review-list"><header><h3>الطلبات · {filtered.length}</h3></header>{filtered.length?filtered.map(x=><button key={x.id} className={selected?.id===x.id?'selected':''} onClick={()=>{setSelected(x);setMatched(false);setNote('');setReason('')}}><span><b>{x.orders?.order_number}</b><small>{x.orders?.customers?.name} · {x.orders?.customers?.phone}</small></span><strong>{money(x.orders?.total_sar)}</strong><small>{date(x.submitted_at)}</small></button>):<div className="commerce-empty">لا توجد تحويلات في هذه الحالة.</div>}</section>
   <section className="commerce-panel bank-review-detail">{selected?<><header><h3>{selected.orders?.order_number}</h3><Status value={selected.status}/></header><div className="review-detail-body"><div className="review-summary"><Info label="العميل" value={selected.orders?.customers?.name}/><Info label="الجوال" value={selected.orders?.customers?.phone}/><Info label="البريد" value={selected.orders?.customers?.email}/><Info label="العنوان" value={`${selected.orders?.addresses?.city||''} · ${selected.orders?.addresses?.district||''} · ${selected.orders?.addresses?.street||''}`}/><Info label="المبلغ المطلوب" value={money(selected.orders?.total_sar)}/><Info label="وقت رفع الإيصال" value={date(selected.submitted_at)}/><Info label="اسم المحوّل" value={selected.sender_name||'غير مضاف'}/><Info label="آخر 4 أرقام" value={selected.sender_account_last4||'غير مضافة'}/></div><div className="review-products"><h4>المنتجات</h4>{selected.orders?.order_items?.map((i,n)=><div key={n}><span>{i.product_name} · {i.sku}</span><b>{i.quantity} × {money(i.unit_price_sar)}</b></div>)}</div><div className="receipt-view"><h4>الإيصال الخاص</h4>{selected.receiptSignedUrl?<><a href={selected.receiptSignedUrl} target="_blank" rel="noreferrer">فتح الإيصال في نافذة آمنة ↗</a>{selected.mime_type?.startsWith('image/')&&<img src={selected.receiptSignedUrl} alt="إيصال التحويل"/>}</>:<p>تعذر إنشاء رابط مؤقت للإيصال.</p>}<small>الرابط مؤقت لمدة 10 دقائق، والملف محفوظ في Private Storage.</small></div>{selected.status==='under_review'&&<div className="review-actions"><div className="bank-proof-warning"><b>تنبيه تحقق</b><p>صورة الإيصال ليست دليل دفع كافيًا. افتحي الحساب البنكي وتحققي من وصول المبلغ الصحيح وربطه بهذا الطلب.</p></div><label className="bank-match-check"><input type="checkbox" checked={matched} onChange={e=>setMatched(e.target.checked)}/><span>تحققت بنفسي من وصول ومطابقة المبلغ في الحساب البنكي.</span></label><label>ملاحظة داخلية<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="اختياري"/></label><button className="solid confirm-payment" disabled={!matched||busy} onClick={confirm}>{busy==='confirm'?'جاري التأكيد...':'Confirm Payment · تأكيد استلام المبلغ'}</button><div className="reject-box"><label>سبب الرفض<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="مثال: المبلغ لم يصل / المبلغ غير مطابق"/></label><button disabled={!reason.trim()||busy} onClick={reject}>{busy==='reject'?'جاري الرفض...':'رفض التحويل وإطلاق المخزون'}</button></div></div>}{selected.status!=='under_review'&&<div className="review-closed"><Info label="وقت القرار" value={date(selected.verified_at)}/>{selected.rejection_reason&&<Info label="سبب الرفض" value={selected.rejection_reason}/>} {selected.admin_note&&<Info label="ملاحظة الأدمن" value={selected.admin_note}/>}</div>}</div></>:<div className="commerce-empty">اختاري تحويلًا من القائمة لعرض تفاصيله.</div>}</section></div>}</main>
 </div>
}
function Info({label,value}){return <div><small>{label}</small><b>{value||'—'}</b></div>}
function Status({value}){return <span className={`status status-${value}`}>{labels[value]||value}</span>}
