import { useEffect, useMemo, useState } from 'react'

const API=import.meta.env.VITE_ADMIN_API_URL||'https://asubcanztloxiddshakz.supabase.co/functions/v1/crown-admin-api'
const TOKEN_KEY='crown_admin_session'
const token=()=>sessionStorage.getItem(TOKEN_KEY)||''
async function request(path,options={}){const r=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json',...(token()?{Authorization:`Bearer ${token()}`}:{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||'request_failed'),{status:r.status,data:d});return d}
const money=v=>`${Number(v||0).toLocaleString('ar-SA',{maximumFractionDigits:2})} ر.س`
const date=v=>v?new Date(v).toLocaleString('ar-SA'):'—'
const blankProduct={slug:'',name_ar:'',name_en:'',description_ar:'',description_en:'',price_sar:0,size_label:'',sku:'',stock_qty:0,active:true,product_images:[]}

export default function CommerceAdmin({onOpenSite}){
 const[section,setSection]=useState('dashboard'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[dashboard,setDashboard]=useState(null),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[customers,setCustomers]=useState([]),[payments,setPayments]=useState([]),[shipments,setShipments]=useState([]),[media,setMedia]=useState([]),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false)
 const tabs={dashboard:'نظرة عامة',products:'المنتجات والمخزون',orders:'الطلبات',customers:'العملاء',payments:'الدفعات',shipments:'الشحن'}
 async function loadAll(){setLoading(true);setError('');try{const[d,p,o,c,pa,s,m]=await Promise.all([request('/commerce/dashboard'),request('/commerce/products'),request('/commerce/orders'),request('/commerce/customers'),request('/commerce/payments'),request('/commerce/shipments'),request('/media')]);setDashboard(d);setProducts(p.products||[]);setOrders(o.orders||[]);setCustomers(c.customers||[]);setPayments(pa.payments||[]);setShipments(s.shipments||[]);setMedia(m.media||[])}catch(e){setError(e.status===401?'انتهت جلسة الإدارة. سجّل الدخول من محرر الموقع أولًا.':'تعذر تحميل بيانات Commerce.')}finally{setLoading(false)}}
 useEffect(()=>{if(!token()){setLoading(false);setError('انتهت جلسة الإدارة. سجّل الدخول من محرر الموقع أولًا.');return}loadAll()},[])
 const low=useMemo(()=>products.filter(p=>Number(p.stock_qty)<=5),[products])
 async function saveProduct(){setSaving(true);setError('');try{const isNew=!editing.id;const path=isNew?'/commerce/products':`/commerce/products/${editing.id}`;const payload={...editing,product_images:(editing.product_images||[]).map((x,i)=>({url:x.url,alt_text:x.alt_text||'',position:i}))};const r=await request(path,{method:isNew?'POST':'PUT',body:JSON.stringify(payload)});setProducts(list=>isNew?[r.product,...list]:list.map(p=>p.id===r.product.id?r.product:p));setEditing(null);const d=await request('/commerce/dashboard');setDashboard(d)}catch(e){setError(e.data?.error==='missing_required_fields'?'أكمل الاسم العربي وSKU وSlug.':'تعذر حفظ المنتج. تحقق من SKU وSlug والصور.')}finally{setSaving(false)}}
 async function changeOrderStatus(id,status){try{const r=await request(`/commerce/orders/${id}/status`,{method:'PUT',body:JSON.stringify({status})});setOrders(list=>list.map(o=>o.id===id?{...o,status:r.order.status}:o));const d=await request('/commerce/dashboard');setDashboard(d)}catch{setError('تعذر تحديث حالة الطلب.')}}
 if(error&&error.includes('سجّل الدخول')&&!token())return <main className="commerce-auth"><img src="/Crown-Oil-Hier/crown-logo.png" alt="Crown"/><h1>Commerce Admin</h1><p>{error}</p><button onClick={onOpenSite}>فتح تسجيل الدخول</button></main>
 return <div className="commerce-shell">
   <aside className="commerce-side"><div className="commerce-title"><small>COMMERCE ADMIN</small><h2>إدارة المتجر</h2><p>المنتجات والصور والمخزون هنا هي المصدر الحقيقي للمتجر.</p></div><nav>{Object.entries(tabs).map(([k,v])=><button key={k} className={section===k?'active':''} onClick={()=>setSection(k)}>{v}</button>)}</nav><div className="commerce-side-note"><b>{low.length}</b><span>منتج منخفض المخزون</span></div></aside>
   <main className="commerce-main"><header><div><small>CROWN OPERATIONS</small><h1>{tabs[section]}</h1></div><div><button onClick={loadAll}>تحديث البيانات</button>{section==='products'&&<button className="solid" onClick={()=>setEditing({...blankProduct})}>+ منتج</button>}</div></header>{error&&<div className="commerce-error">{error}</div>}{loading?<div className="commerce-loading">جاري تحميل بيانات المتجر...</div>:<>
   {section==='dashboard'&&dashboard&&<div className="commerce-dashboard"><div className="metric-grid"><Metric label="الطلبات" value={dashboard.stats.orders}/><Metric label="العملاء" value={dashboard.stats.customers}/><Metric label="المنتجات" value={dashboard.stats.products}/><Metric label="الإيراد المدفوع" value={money(dashboard.stats.revenue)}/></div><Panel title="مخزون يحتاج متابعة"><div className="simple-list">{dashboard.lowStock?.length?dashboard.lowStock.map(p=><div key={p.id}><span><b>{p.name_ar||p.name_en}</b><small>{p.sku}</small></span><strong>{p.stock_qty}</strong></div>):<Empty text="لا توجد منتجات منخفضة المخزون"/>}</div></Panel><Panel title="آخر الطلبات"><OrderTable orders={dashboard.recentOrders||[]} compact changeStatus={changeOrderStatus}/></Panel></div>}
   {section==='products'&&<Panel title={`المنتجات · ${products.length}`}><div className="table-scroll"><table><thead><tr><th>المنتج</th><th>الصور</th><th>SKU</th><th>السعر</th><th>المخزون</th><th>الحالة</th><th></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name_ar||p.name_en}</b><small>{p.size_label}</small></td><td>{p.product_images?.length||0}</td><td>{p.sku}</td><td>{money(p.price_sar)}</td><td><span className={Number(p.stock_qty)<=5?'stock-low':''}>{p.stock_qty}</span></td><td><Status value={p.active?'active':'inactive'}/></td><td><button onClick={()=>setEditing({...p,product_images:[...(p.product_images||[])]})}>تحرير</button></td></tr>)}</tbody></table></div></Panel>}
   {section==='orders'&&<Panel title={`الطلبات · ${orders.length}`}><OrderTable orders={orders} changeStatus={changeOrderStatus}/></Panel>}
   {section==='customers'&&<Panel title={`العملاء · ${customers.length}`}><div className="table-scroll"><table><thead><tr><th>العميل</th><th>التواصل</th><th>عدد الطلبات</th><th>المدفوع</th><th>تاريخ التسجيل</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><b>{c.name||'بدون اسم'}</b></td><td>{c.phone||c.email||'—'}<small>{c.email&&c.phone?c.email:''}</small></td><td>{c.orders}</td><td>{money(c.spent)}</td><td>{date(c.created_at)}</td></tr>)}</tbody></table></div></Panel>}
   {section==='payments'&&<Panel title={`الدفعات · ${payments.length}`}><div className="table-scroll"><table><thead><tr><th>الطلب</th><th>المزود</th><th>الطريقة</th><th>الحالة</th><th>المبلغ</th><th>التاريخ</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.orders?.order_number||'—'}</td><td>{p.provider||'—'}</td><td>{p.method||'—'}</td><td><Status value={p.status}/></td><td>{money(p.amount_sar)}</td><td>{date(p.created_at)}</td></tr>)}</tbody></table></div>{!payments.length&&<Empty text="لا توجد دفعات حتى الآن. بوابة الدفع الإنتاجية لم تُفعّل بعد."/>}</Panel>}
   {section==='shipments'&&<Panel title={`الشحنات · ${shipments.length}`}><div className="table-scroll"><table><thead><tr><th>الطلب</th><th>المزود</th><th>رقم التتبع</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{shipments.map(s=><tr key={s.id}><td>{s.orders?.order_number||'—'}</td><td>{s.provider||'—'}</td><td>{s.tracking_number||'—'}</td><td><Status value={s.status}/></td><td>{date(s.created_at)}</td></tr>)}</tbody></table></div>{!shipments.length&&<Empty text="لا توجد شحنات حتى الآن. مزود الشحن الإنتاجي لم يُفعّل بعد."/>}</Panel>}
   </>}</main>
   {editing&&<ProductEditor value={editing} setValue={setEditing} close={()=>setEditing(null)} save={saveProduct} saving={saving} media={media}/>}</div>
}
function Metric({label,value}){return <article className="metric"><small>{label}</small><b>{value}</b></article>}
function Panel({title,children}){return <section className="commerce-panel"><header><h3>{title}</h3></header>{children}</section>}
function Empty({text}){return <div className="commerce-empty">{text}</div>}
function Status({value}){return <span className={`status status-${String(value||'unknown')}`}>{value||'—'}</span>}
function OrderTable({orders,compact=false,changeStatus}){return <div className="table-scroll"><table><thead><tr><th>رقم الطلب</th>{!compact&&<th>العميل</th>}<th>الإجمالي</th><th>الدفع</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.order_number}</b>{!compact&&o.order_items?.length>0&&<small>{o.order_items.map(i=>`${i.product_name} × ${i.quantity}`).join(' · ')}</small>}</td>{!compact&&<td>{o.customers?.name||o.customers?.phone||'—'}</td>}<td>{money(o.total_sar)}</td><td><Status value={o.payment_status}/></td><td><select value={o.status} onChange={e=>changeStatus(o.id,e.target.value)}><option value="pending">pending</option><option value="processing">processing</option><option value="shipped">shipped</option><option value="delivered">delivered</option><option value="cancelled">cancelled</option><option value="refunded">refunded</option></select></td><td>{date(o.created_at)}</td></tr>)}</tbody></table>{!orders.length&&<Empty text="لا توجد طلبات حتى الآن."/>}</div>}
function ProductEditor({value,setValue,close,save,saving,media}){
 const[picker,setPicker]=useState(false),set=(k,v)=>setValue(p=>({...p,[k]:v})),images=value.product_images||[]
 const setImages=next=>set('product_images',next.slice(0,12))
 const addUrl=()=>setImages([...images,{url:'',alt_text:'',position:images.length}])
 const addMedia=m=>{if(images.length>=12)return;setImages([...images,{url:m.url,alt_text:m.alt_text||value.name_ar||'',position:images.length}]);setPicker(false)}
 const updateImage=(i,k,v)=>setImages(images.map((x,n)=>n===i?{...x,[k]:v}:x))
 const removeImage=i=>setImages(images.filter((_,n)=>n!==i))
 const move=(i,d)=>{const j=i+d;if(j<0||j>=images.length)return;const n=[...images];[n[i],n[j]]=[n[j],n[i]];setImages(n)}
 return <div className="product-modal" onMouseDown={close}><section onMouseDown={e=>e.stopPropagation()}><header><div><small>PRODUCT EDITOR</small><h2>{value.id?'تعديل المنتج':'إضافة منتج'}</h2></div><button onClick={close}>×</button></header><div className="product-form"><label>الاسم العربي<input value={value.name_ar||''} onChange={e=>set('name_ar',e.target.value)}/></label><label>الاسم الإنجليزي<input value={value.name_en||''} onChange={e=>set('name_en',e.target.value)}/></label><label>Slug<input dir="ltr" value={value.slug||''} onChange={e=>set('slug',e.target.value)}/></label><label>SKU<input dir="ltr" value={value.sku||''} onChange={e=>set('sku',e.target.value)}/></label><label>السعر<input type="number" min="0" value={value.price_sar||0} onChange={e=>set('price_sar',Number(e.target.value))}/></label><label>الحجم<input value={value.size_label||''} onChange={e=>set('size_label',e.target.value)}/></label><label>المخزون<input type="number" min="0" value={value.stock_qty||0} onChange={e=>set('stock_qty',Number(e.target.value))}/></label><label className="toggle"><input type="checkbox" checked={!!value.active} onChange={e=>set('active',e.target.checked)}/> المنتج نشط</label><label className="wide">الوصف العربي<textarea value={value.description_ar||''} onChange={e=>set('description_ar',e.target.value)}/></label><label className="wide">الوصف الإنجليزي<textarea value={value.description_en||''} onChange={e=>set('description_en',e.target.value)}/></label>
 <div className="wide product-gallery-editor"><div className="gallery-editor-head"><div><b>صور المنتج</b><small>الصورة الأولى هي الصورة الرئيسية · الحد الأقصى 12 صورة</small></div><div><button type="button" onClick={()=>setPicker(!picker)}>+ من Media Library</button><button type="button" onClick={addUrl}>+ رابط صورة</button></div></div>{picker&&<div className="gallery-media-picker">{media.length?media.map(m=><button type="button" key={m.id} onClick={()=>addMedia(m)}><img src={m.url} alt={m.alt_text||''}/><span>{m.alt_text||'اختيار'}</span></button>):<p>لا توجد صور في Media Library.</p>}</div>}<div className="gallery-images-list">{images.map((img,i)=><article key={`${img.id||img.url}-${i}`}><div className="gallery-thumb">{img.url?<img src={img.url} alt=""/>:<span>{i+1}</span>}</div><div><label>رابط الصورة<input dir="ltr" value={img.url||''} onChange={e=>updateImage(i,'url',e.target.value)}/></label><label>Alt Text<input value={img.alt_text||''} onChange={e=>updateImage(i,'alt_text',e.target.value)}/></label></div><aside><button type="button" disabled={i===0} onClick={()=>move(i,-1)}>↑</button><button type="button" disabled={i===images.length-1} onClick={()=>move(i,1)}>↓</button><button type="button" className="danger" onClick={()=>removeImage(i)}>حذف</button></aside></article>)}</div>{!images.length&&<div className="commerce-empty">لم تتم إضافة صور لهذا المنتج بعد.</div>}</div>
 </div><footer><button onClick={close}>إلغاء</button><button className="solid" disabled={saving} onClick={save}>{saving?'جاري الحفظ...':'حفظ المنتج'}</button></footer></section></div>}
